# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63f499bbd9c2b6fe52bc2d08b39f7de79322bead5e5634327fab64a8bbf58de0a75c0ae157a2057f128109b3fbb407adf70dee6d9f0fd01c9ab0716f851d3024

test:
  secret_key_base: 6fab4878fed8eff665bc5a919ee86ec6952f615b2773b559747fe12670e645f81989f2ef49262f4f8334a020890917a84eba875e9942aab7ead6c7a73b4f0552

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
